### PR TITLE
Added follow the route example

### PR DESCRIPTION
**Pull request by nampi**

### CODE REVIEW

**Comment by nampi** [comment]
@tfoote If I add "self.move_base.cancel_goal()" in shutdown function (file go_to_specific_point_on_map.py) I have this error: "[ERROR] [WallTime: 1453602721.887969] [252.450000] Received comm state PREEMPTING when in simple state DONE with SimpleActionClient in NS /move_base".

**Comment by tfoote** [comment]
In your on_shutdown you should check if the goal is active before calling `cancel`. If it achieved your goal, or previously canceled it it doesn't need to be canceled.

**Comment by nampi** [comment]
@tfoote I have updated it. TurtleBot doesn't move after Ctrl-C. I have no problem with it.
If I press Ctrl-C before start moving then I have this output (correct in my opinion):

```
nadya@nampi:~/code/tutorial/turtlebot$ python follow_the_route.py
[INFO] [WallTime: 1453992476.989002] [0.000000] Wait for the action server to come up
^C[INFO] [WallTime: 1453992477.357342] [301.240000] Stop
[INFO] [WallTime: 1453992478.500628] [302.250000] Ctrl-C caught. Quitting
```

If I press Ctrl-C when TurtleBot is going to the goal, then the output is not correct. I have a lot of info strings (see below). There is no such string " Ctrl-C caught. Quitting".

```
nadya@nampi:~/code/tutorial/turtlebot$ python follow_the_route.py
[INFO] [WallTime: 1453992717.379277] [541.080000] Wait for the action server to come up
[INFO] [WallTime: 1453992718.658118] [542.360000] Go to dumpster pose
^C[INFO] [WallTime: 1453992720.160337] [543.860000] Stop
[INFO] [WallTime: 1453992721.782606] [544.860000] Failed to reach dumpster pose
[INFO] [WallTime: 1453992721.782872] [544.860000] Go to cube_20k pose
[INFO] [WallTime: 1453992721.783233] [544.860000] Failed to reach cube_20k pose
[INFO] [WallTime: 1453992721.783394] [544.860000] Go to bookshelf pose
[INFO] [WallTime: 1453992721.783704] [544.860000] Failed to reach bookshelf pose
```

Why is program working after Ctrl-C signal?

**Comment by tfoote** [comment]
I believe the reason that you are failing the other goals quickly is that your callback cancels your current goal. And then the for loop continues. But the new goals detect that rospy is shutdown and instantly fail themselves. 

The solution is to check rospy.is_shutdown() during your loop and break out of the loop.

**Comment by tfoote** [comment]
Looks good.

**Pull request merged**
