### PR TITLE
Added my_turtlebot_follower

### PR DESCRIPTION
**Pull request by nampi**

### CODE REVIEW

**Comment by tfoote** [comment]
This package should also be renamed like #4

**Comment by nampi** [comment]
@tfoote 
1) How do you check so big commit?
2) Can I change only launches file? I didn't change anything else. 
3) Should I change nodelet names in follower.launch file?

**Comment by tfoote** [comment]
Typically you want to break it into two commits. One is the straight copy, and the 2nd is the changes. That way you only need to review the changes. 

In general it's much arder. 

Since you're not overlaying now you can decrease the amount of duplication. In particular I think that you've only changed the same changes as: https://github.com/turtlebot/turtlebot_apps/pull/142/files in which case you should not add these files into this repo, but instruct people to checkout the patched version of the follower from the upstream repo. (Currently with your branch in the pull-request. In the future they can pull it once it's merged.)

**Comment by tfoote** [comment]
To validate this I moved a few directories to make the layout the same as a default checkout of turtlebot_apps/turtlebot_follower see the meld highlighting. 

turtlebot_follower_diff

**Comment by nampi** [comment]
@tfoote 
Do you recommend to change the lesson instructions:
1. Create folder called my_turtlebot_follower
2. Clone turtlebot_follower from here https://github.com/turtlebot/turtlebot_apps/tree/indigo/turtlebot_follower 
3. Change branch to nampi:simul 
What do you mean "you should not add these files into this repo, but instruct people to checkout the patched version of the follower from the upstream repo. (Currently with your branch in the pull-request. In the future they can pull it once it's merged.)"?

**Comment by tfoote** [comment]
1. Create a workspace with a `src` directory
2. Clone this repo into it
3. Clone https://github.com/turtlebot/turtlebot_apps/tree/indigo/turtlebot_follower into it (temporarily change to use https://github.com/nampi/turtlebot_apps/ with branch simul until https://github.com/turtlebot/turtlebot_apps/pull/142 is merged)

In this case we are explicitly overlaying with a changed version of the package so we won't change the name of the package.

**Pull request closed without merging**
